# Generated by Django 4.0 on 2022-01-02 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgettracker_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='last_log',
            field=models.DateTimeField(default=0, null=True),
        ),
    ]
