# Generated by Django 4.0 on 2022-01-05 19:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgettracker_app', '0002_alter_user_last_log'),
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_name', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='account_created',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_log',
            field=models.DateTimeField(null=True),
        ),
    ]
