# Generated by Django 4.0 on 2022-01-06 12:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('budgettracker_app', '0003_session_alter_user_account_created_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('description', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='budgettracker_app.user')),
            ],
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('value', models.DecimalField(decimal_places=2, max_digits=9)),
                ('pay_month', models.DateField()),
                ('pay_year', models.DateField()),
                ('deadline', models.DateField(null=True)),
                ('continuity', models.BooleanField(default=False)),
                ('continuity_months', models.IntegerField(default=1)),
                ('is_paid', models.BooleanField(default=False)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='budgettracker_app.category')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='budgettracker_app.user')),
            ],
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('mod_date', models.DateField()),
                ('expense', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='budgettracker_app.expense')),
            ],
        ),
        migrations.CreateModel(
            name='Archive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('value', models.DecimalField(decimal_places=2, max_digits=9)),
                ('paid_date', models.DateField()),
                ('expanse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='budgettracker_app.expense')),
            ],
        ),
    ]
