# Generated by Django 4.0 on 2022-01-16 14:51

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('budgettracker_app', '0008_rename_expanse_archive_expense_note_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='exp_create',
            field=models.DateField(default=datetime.datetime(2022, 1, 16, 14, 51, 45, 7708, tzinfo=utc)),
        ),
        migrations.DeleteModel(
            name='Archive',
        ),
    ]
