# Generated by Django 4.0 on 2022-01-16 14:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('budgettracker_app', '0009_expense_exp_create_delete_archive'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='exp_create',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
