# Generated by Django 4.0 on 2022-01-16 15:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgettracker_app', '0010_alter_expense_exp_create'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='exp_create',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
