# Generated by Django 4.0 on 2022-01-18 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgettracker_app', '0011_alter_expense_exp_create'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='next_exp',
            field=models.DateField(null=True),
        ),
    ]
