# Generated by Django 4.0 on 2022-01-18 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgettracker_app', '0014_remove_expense_continuity_step'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expense',
            old_name='continuity_amount',
            new_name='exp_amount',
        ),
        migrations.RemoveField(
            model_name='expense',
            name='exp_create',
        ),
        migrations.AddField(
            model_name='expense',
            name='create',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='expense',
            name='period_delta',
            field=models.CharField(default=0, max_length=64),
            preserve_default=False,
        ),
    ]
