# Generated by Django 4.0 on 2022-01-21 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgettracker_app', '0016_expense_paid_date_archive'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='new_note',
            field=models.TextField(null=True),
        ),
    ]
